language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.10

install:
  - pip install -q Django==$DJANGO_VERSION
  - "make install"

script: coverage run --source=django_thumbor manage.py test

after_success:
    coveralls
