language: python

python:
  - 2.7
  - 3.5.2

env:
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - "make install"

script: coverage run --source=django_thumbor manage.py test

after_success:
    coveralls
